## 🚗 Car Insurance Claim Prediction
## End-to-End Machine Learning Pipeline

In this notebook we will:

- Explore the dataset
- Clean the data
- Handle missing values
- Build preprocessing pipelines
- Compare multiple ML models
- Tune the best model
- Train the final model

In [1]:
# Import Libraries
# ==========================
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
# Load Dataset
# ==========================

df = pd.read_csv('/kaggle/input/datasets/xiaomengsun/car-insurance-claim-data/car_insurance_claim.csv')
df

,ID,KIDSDRIV,BIRTH,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,MSTATUS,GENDER,EDUCATION,OCCUPATION,TRAVTIME,CAR_USE,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CLM_AMT,CAR_AGE,CLAIM_FLAG,URBANICITY
0,63581743,0,16MAR39,60.0,0,11.0,"$67,349",No,$0,z_No,M,PhD,Professional,14,Private,"$14,230",11,Minivan,yes,"$4,461",2,No,3,$0,18.0,0,Highly Urban/ Urban
1,132761049,0,21JAN56,43.0,0,11.0,"$91,449",No,"$257,252",z_No,M,z_High School,z_Blue Collar,22,Commercial,"$14,940",1,Minivan,yes,$0,0,No,0,$0,1.0,0,Highly Urban/ Urban
2,921317019,0,18NOV51,48.0,0,11.0,"$52,881",No,$0,z_No,M,Bachelors,Manager,26,Private,"$21,970",1,Van,yes,$0,0,No,2,$0,10.0,0,Highly Urban/ Urban
3,727598473,0,05MAR64,35.0,1,10.0,"$16,039",No,"$124,191",Yes,z_F,z_High School,Clerical,5,Private,"$4,010",4,z_SUV,no,"$38,690",2,No,3,$0,10.0,0,Highly Urban/ Urban
4,450221861,0,05JUN48,51.0,0,14.0,NaN,No,"$306,251",Yes,M,<High School,z_Blue Collar,32,Private,"$15,440",7,Minivan,yes,$0,0,No,0,$0,6.0,0,Highly Urban/ Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10297,67790126,1,13AUG54,45.0,2,9.0,"$164,669",No,"$386,273",Yes,M,PhD,Manager,21,Private,"$13,270",15,Minivan,no,$0,0,No,2,$0,17.0,0,Highly Urban/ Urban
10298,61970712,0,17JUN53,46.0,0,9.0,"$107,204",No,"$332,591",Yes,M,Masters,NaN,36,Commercial,"$24,490",6,Panel Truck,no,$0,0,No,0,$0,1.0,0,Highly Urban/ Urban
10299,849208064,0,18JUN51,48.0,0,15.0,"$39,837",No,"$170,611",Yes,z_F,<High School,z_Blue Collar,12,Private,"$13,820",7,z_SUV,no,$0,0,No,0,$0,1.0,0,Highly Urban/ Urban
10300,627828331,0,12DEC48,50.0,0,7.0,"$43,445",No,"$149,248",Yes,z_F,Bachelors,Home Maker,36,Private,"$22,550",6,Minivan,no,$0,0,No,0,$0,11.0,0,Highly Urban/ Urban
10301,680381960,0,27FEB47,52.0,0,11.0,"$53,235",No,"$197,017",Yes,z_F,z_High School,Clerical,64,Private,"$19,400",6,Minivan,no,$0,0,No,0,$0,9.0,0,z_Highly Rural/ Rural

# 🚗 Car Insurance Claim Prediction

## 📌 Project Overview

The objective of this project is to predict whether a customer will file an insurance claim using demographic, financial, driving history, and vehicle-related information.

The workflow includes:

- Data Cleaning
- Exploratory Data Analysis (EDA)
- Feature Engineering
- Data Preprocessing
- Model Comparison
- Hyperparameter Tuning
- Final Model Selection

---

## 📊 Dataset Description

## 📋 Dataset Columns Description

| Column | Description | Data Type |
|--------|-------------|-----------|
| **ID** | Unique identifier for each customer. | Integer |
| **KIDSDRIV** | Number of children who drive in the household. | Numerical |
| **BIRTH** | Customer's date of birth. | Date |
| **AGE** | Age of the customer. | Numerical |
| **HOMEKIDS** | Number of children living at home. | Numerical |
| **YOJ** | Years at current job (Years On Job). | Numerical |
| **INCOME** | Annual income of the customer. | Numerical |
| **PARENT1** | Indicates whether the customer is a single parent (Yes/No). | Categorical |
| **HOME_VAL** | Estimated value of the customer's home. | Numerical |
| **MSTATUS** | Marital status of the customer. | Categorical |
| **GENDER** | Gender of the customer. | Categorical |
| **EDUCATION** | Highest education level attained. | Ordinal |
| **OCCUPATION** | Customer's occupation. | Categorical |
| **TRAVTIME** | Average travel time to work (minutes). | Numerical |
| **CAR_USE** | Primary usage of the insured vehicle (Private or Commercial). | Categorical |
| **BLUEBOOK** | Estimated market value of the vehicle. | Numerical |
| **TIF** | Time In Force (years insured with the company). | Numerical |
| **CAR_TYPE** | Type of the insured vehicle (SUV, Sedan, Van, etc.). | Categorical |
| **RED_CAR** | Indicates whether the vehicle is red. | Binary |
| **OLDCLAIM** | Total amount of previous insurance claims. | Numerical |
| **CLM_FREQ** | Number of previous insurance claims. | Numerical |
| **REVOKED** | Whether the driver's license has ever been revoked. | Binary |
| **MVR_PTS** | Motor Vehicle Record points (traffic violations). | Numerical |
| **CLM_AMT** | Amount of the current claim (**Data Leakage - Removed from training**). | Numerical |
| **CAR_AGE** | Age of the insured vehicle in years. | Numerical |
| **CLAIM_FLAG** | **Target Variable**. Indicates whether a claim was filed (0 = No, 1 = Yes). | Binary |
| **URBANICITY** | Customer's residential area (Urban or Rural). | Categorical |

## 📊 Dataset Overview

In [4]:
# Check data types 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10302 entries, 0 to 10301
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10302 non-null  int64
 1   KIDSDRIV    10302 non-null  int64
 2   BIRTH       10302 non-null  object
 3   AGE         10295 non-null  float64
 4   HOMEKIDS    10302 non-null  int64
 5   YOJ         9754 non-null   float64
 6   INCOME      9732 non-null   object
 7   PARENT1     10302 non-null  object
 8   HOME_VAL    9727 non-null   object
 9   MSTATUS     10302 non-null  object
 10  GENDER      10302 non-null  object
 11  EDUCATION   10302 non-null  object
 12  OCCUPATION  9637 non-null   object
 13  TRAVTIME    10302 non-null  int64
 14  CAR_USE     10302 non-null  object
 15  BLUEBOOK    10302 non-null  object
 16  TIF         10302 non-null  int64
 17  CAR_TYPE    10302 non-null  object
 18  RED_CAR     10302 non-null  object
 19  OLDCLAIM    10302 non-null  object
 20  CLM_FREQ    10302 non-null  int64
 21  REVOKED     10302 non-null  object
 22  MVR_PTS     10302 non-null  int64
 23  CLM_AMT     10302 non-null  object
 24  CAR_AGE     9663 non-null   float64
 25  CLAIM_FLAG  10302 non-null  int64
 26  URBANICITY  10302 non-null  object
dtypes: float64(3), int64(8), object(16)
memory usage: 2.1+ MB

* Check summary statistics for `Numerical` columns

In [5]:
df.describe(include='number').round(2)

,ID,KIDSDRIV,AGE,HOMEKIDS,YOJ,TRAVTIME,TIF,CLM_FREQ,MVR_PTS,CAR_AGE,CLAIM_FLAG
count,1.030200e+04,10302.00,10295.00,10302.00,9754.00,10302.00,10302.00,10302.00,10302.00,9663.00,10302.00
mean,4.956631e+08,0.17,44.84,0.72,10.47,33.42,5.33,0.80,1.71,8.30,0.27
std,2.864675e+08,0.51,8.61,1.12,4.11,15.87,4.11,1.15,2.16,5.71,0.44
min,6.317500e+04,0.00,16.00,0.00,0.00,5.00,1.00,0.00,0.00,-3.00,0.00
25%,2.442869e+08,0.00,39.00,0.00,9.00,22.00,1.00,0.00,0.00,1.00,0.00
50%,4.970043e+08,0.00,45.00,0.00,11.00,33.00,4.00,0.00,1.00,8.00,0.00
75%,7.394551e+08,0.00,51.00,1.00,13.00,44.00,7.00,2.00,3.00,12.00,1.00
max,9.999264e+08,4.00,81.00,5.00,23.00,142.00,25.00,5.00,13.00,28.00,1.00

* Check summary statistics for `Categorical` columns

In [6]:
df.describe(include='object')

,BIRTH,INCOME,PARENT1,HOME_VAL,MSTATUS,GENDER,EDUCATION,OCCUPATION,CAR_USE,BLUEBOOK,CAR_TYPE,RED_CAR,OLDCLAIM,REVOKED,CLM_AMT,URBANICITY
count,10302,9732,10302,9727,10302,10302,10302,9637,10302,10302,10302,10302,10302,10302,10302,10302
unique,6560,8151,2,6334,2,2,5,8,2,2985,6,2,3545,2,2346,2
top,20OCT60,$0,No,$0,Yes,z_F,z_High School,z_Blue Collar,Private,"$1,500",z_SUV,no,$0,No,$0,Highly Urban/ Urban
freq,8,797,8959,2908,6188,5545,2952,2288,6513,207,2883,7326,6292,9041,7556,8230

In [7]:
# Check  duplicates
df.duplicated().sum()

np.int64(1)

In [8]:
df.drop_duplicates(inplace= True, ignore_index= True)
df.reset_index(inplace=True)

In [9]:
# Check Missing Values
df.isna().sum()

index           0
ID              0
KIDSDRIV        0
BIRTH           0
AGE             7
HOMEKIDS        0
YOJ           548
INCOME        570
PARENT1         0
HOME_VAL      575
MSTATUS         0
GENDER          0
EDUCATION       0
OCCUPATION    665
TRAVTIME        0
CAR_USE         0
BLUEBOOK        0
TIF             0
CAR_TYPE        0
RED_CAR         0
OLDCLAIM        0
CLM_FREQ        0
REVOKED         0
MVR_PTS         0
CLM_AMT         0
CAR_AGE       639
CLAIM_FLAG      0
URBANICITY      0
dtype: int64

In [10]:
df.isna().mean().round(4) * 100

index         0.00
ID            0.00
KIDSDRIV      0.00
BIRTH         0.00
AGE           0.07
HOMEKIDS      0.00
YOJ           5.32
INCOME        5.53
PARENT1       0.00
HOME_VAL      5.58
MSTATUS       0.00
GENDER        0.00
EDUCATION     0.00
OCCUPATION    6.46
TRAVTIME      0.00
CAR_USE       0.00
BLUEBOOK      0.00
TIF           0.00
CAR_TYPE      0.00
RED_CAR       0.00
OLDCLAIM      0.00
CLM_FREQ      0.00
REVOKED       0.00
MVR_PTS       0.00
CLM_AMT       0.00
CAR_AGE       6.20
CLAIM_FLAG    0.00
URBANICITY    0.00
dtype: float64

## 🧹 Data Cleaning

In [11]:
# make all column names lowercase
df.columns = df.columns.str.lower().str.strip()
df.columns

Index(['index', 'id', 'kidsdriv', 'birth', 'age', 'homekids', 'yoj', 'income',
       'parent1', 'home_val', 'mstatus', 'gender', 'education', 'occupation',
       'travtime', 'car_use', 'bluebook', 'tif', 'car_type', 'red_car',
       'oldclaim', 'clm_freq', 'revoked', 'mvr_pts', 'clm_amt', 'car_age',
       'claim_flag', 'urbanicity'],
      dtype='object')

- Remove unnecessary columns

In [12]:
df.drop(['id', 'birth','index'], axis= 1, inplace= True)

In [13]:
df.duplicated().sum()

np.int64(0)

-  Clean categorical values

In [14]:
df[['income', 'home_val', 'bluebook', 'oldclaim', 'clm_amt']]

         income  home_val bluebook oldclaim clm_amt
0       $67,349        $0  $14,230   $4,461      $0
1       $91,449  $257,252  $14,940       $0      $0
2       $52,881        $0  $21,970       $0      $0
3       $16,039  $124,191   $4,010  $38,690      $0
4           NaN  $306,251  $15,440       $0      $0
...         ...       ...      ...      ...     ...
10296  $164,669  $386,273  $13,270       $0      $0
10297  $107,204  $332,591  $24,490       $0      $0
10298   $39,837  $170,611  $13,820       $0      $0
10299   $43,445  $149,248  $22,550       $0      $0
10300   $53,235  $197,017  $19,400       $0      $0

[10301 rows x 5 columns]

In [15]:
clean_cols = ['income', 'home_val', 'bluebook', 'oldclaim', 'clm_amt']
clean_cols

['income', 'home_val', 'bluebook', 'oldclaim', 'clm_amt']

In [16]:
def clean_num(x):
    if type(x) == float:
        return x
    
    else:
        return x.replace('$', '').replace(',', '')
    
for col in clean_cols:

    df[col] = df[col].apply(clean_num).astype('float')

df[clean_cols]

         income  home_val  bluebook  oldclaim  clm_amt
0       67349.0       0.0   14230.0    4461.0      0.0
1       91449.0  257252.0   14940.0       0.0      0.0
2       52881.0       0.0   21970.0       0.0      0.0
3       16039.0  124191.0    4010.0   38690.0      0.0
4           NaN  306251.0   15440.0       0.0      0.0
...         ...       ...       ...       ...      ...
10296  164669.0  386273.0   13270.0       0.0      0.0
10297  107204.0  332591.0   24490.0       0.0      0.0
10298   39837.0  170611.0   13820.0       0.0      0.0
10299   43445.0  149248.0   22550.0       0.0      0.0
10300   53235.0  197017.0   19400.0       0.0      0.0

[10301 rows x 5 columns]

In [17]:
clean_cols_cat = ['gender', 'education', 'occupation', 'car_type']

df[clean_cols_cat]

      gender      education     occupation     car_type
0          M            PhD   Professional      Minivan
1          M  z_High School  z_Blue Collar      Minivan
2          M      Bachelors        Manager          Van
3        z_F  z_High School       Clerical        z_SUV
4          M   <High School  z_Blue Collar      Minivan
...      ...            ...            ...          ...
10296      M            PhD        Manager      Minivan
10297      M        Masters            NaN  Panel Truck
10298    z_F   <High School  z_Blue Collar        z_SUV
10299    z_F      Bachelors     Home Maker      Minivan
10300    z_F  z_High School       Clerical      Minivan

[10301 rows x 4 columns]

In [18]:
for col in clean_cols_cat:
    df[col] = df[col].str.replace('z_', '')


df[clean_cols_cat]

      gender     education    occupation     car_type
0          M           PhD  Professional      Minivan
1          M   High School   Blue Collar      Minivan
2          M     Bachelors       Manager          Van
3          F   High School      Clerical          SUV
4          M  <High School   Blue Collar      Minivan
...      ...           ...           ...          ...
10296      M           PhD       Manager      Minivan
10297      M       Masters           NaN  Panel Truck
10298      F  <High School   Blue Collar          SUV
10299      F     Bachelors    Home Maker      Minivan
10300      F   High School      Clerical      Minivan

[10301 rows x 4 columns]

In [19]:
# in depth check for categorical columns
cat_cols=df.select_dtypes(include='object').columns
cat_cols

Index(['parent1', 'mstatus', 'gender', 'education', 'occupation', 'car_use',
       'car_type', 'red_car', 'revoked', 'urbanicity'],
      dtype='object')

In [20]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('#' * 50)

parent1
2
['No' 'Yes']
##################################################
mstatus
2
['z_No' 'Yes']
##################################################
gender
2
['M' 'F']
##################################################
education
5
['PhD' 'High School' 'Bachelors' '<High School' 'Masters']
##################################################
occupation
8
['Professional' 'Blue Collar' 'Manager' 'Clerical' 'Doctor' 'Lawyer' nan
 'Home Maker' 'Student']
##################################################
car_use
2
['Private' 'Commercial']
##################################################
car_type
6
['Minivan' 'Van' 'SUV' 'Sports Car' 'Panel Truck' 'Pickup']
##################################################
red_car
2
['yes' 'no']
##################################################
revoked
2
['No' 'Yes']
##################################################
urbanicity
2
['Highly Urban/ Urban' 'z_Highly Rural/ Rural']
##################################################

In [21]:
df['mstatus'] = df['mstatus'].str.replace('z_', '')
df['urbanicity'] = df['urbanicity'].str.replace('z_', '')

In [22]:
# in depth check for numerical columns
num_cols=df.select_dtypes(include='number').columns
num_cols

Index(['kidsdriv', 'age', 'homekids', 'yoj', 'income', 'home_val', 'travtime',
       'bluebook', 'tif', 'oldclaim', 'clm_freq', 'mvr_pts', 'clm_amt',
       'car_age', 'claim_flag'],
      dtype='object')

In [23]:
df['mstatus'].value_counts()

mstatus
Yes    6187
No     4114
Name: count, dtype: int64

In [24]:
df['urbanicity'].value_counts()

urbanicity
Highly Urban/ Urban    8230
Highly Rural/ Rural    2071
Name: count, dtype: int64

-  ❓ Missing Values

In [25]:
df.isna().mean().round(4) * 100

kidsdriv      0.00
age           0.07
homekids      0.00
yoj           5.32
income        5.53
parent1       0.00
home_val      5.58
mstatus       0.00
gender        0.00
education     0.00
occupation    6.46
travtime      0.00
car_use       0.00
bluebook      0.00
tif           0.00
car_type      0.00
red_car       0.00
oldclaim      0.00
clm_freq      0.00
revoked       0.00
mvr_pts       0.00
clm_amt       0.00
car_age       6.20
claim_flag    0.00
urbanicity    0.00
dtype: float64

In [26]:
# Drop missing values rows in age column (low NaN percentage)
df.dropna(subset= ['age'], inplace= True, ignore_index= True)
df.reset_index(drop= True, inplace= True)

In [27]:
df.isna().mean().round(4) * 100

kidsdriv      0.00
age           0.00
homekids      0.00
yoj           5.32
income        5.53
parent1       0.00
home_val      5.57
mstatus       0.00
gender        0.00
education     0.00
occupation    6.46
travtime      0.00
car_use       0.00
bluebook      0.00
tif           0.00
car_type      0.00
red_car       0.00
oldclaim      0.00
clm_freq      0.00
revoked       0.00
mvr_pts       0.00
clm_amt       0.00
car_age       6.21
claim_flag    0.00
urbanicity    0.00
dtype: float64

In [28]:
df

,kidsdriv,age,homekids,yoj,income,parent1,home_val,mstatus,gender,education,occupation,travtime,car_use,bluebook,tif,car_type,red_car,oldclaim,clm_freq,revoked,mvr_pts,clm_amt,car_age,claim_flag,urbanicity
0,0,60.0,0,11.0,67349.0,No,0.0,No,M,PhD,Professional,14,Private,14230.0,11,Minivan,yes,4461.0,2,No,3,0.0,18.0,0,Highly Urban/ Urban
1,0,43.0,0,11.0,91449.0,No,257252.0,No,M,High School,Blue Collar,22,Commercial,14940.0,1,Minivan,yes,0.0,0,No,0,0.0,1.0,0,Highly Urban/ Urban
2,0,48.0,0,11.0,52881.0,No,0.0,No,M,Bachelors,Manager,26,Private,21970.0,1,Van,yes,0.0,0,No,2,0.0,10.0,0,Highly Urban/ Urban
3,0,35.0,1,10.0,16039.0,No,124191.0,Yes,F,High School,Clerical,5,Private,4010.0,4,SUV,no,38690.0,2,No,3,0.0,10.0,0,Highly Urban/ Urban
4,0,51.0,0,14.0,NaN,No,306251.0,Yes,M,<High School,Blue Collar,32,Private,15440.0,7,Minivan,yes,0.0,0,No,0,0.0,6.0,0,Highly Urban/ Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10289,1,45.0,2,9.0,164669.0,No,386273.0,Yes,M,PhD,Manager,21,Private,13270.0,15,Minivan,no,0.0,0,No,2,0.0,17.0,0,Highly Urban/ Urban
10290,0,46.0,0,9.0,107204.0,No,332591.0,Yes,M,Masters,NaN,36,Commercial,24490.0,6,Panel Truck,no,0.0,0,No,0,0.0,1.0,0,Highly Urban/ Urban
10291,0,48.0,0,15.0,39837.0,No,170611.0,Yes,F,<High School,Blue Collar,12,Private,13820.0,7,SUV,no,0.0,0,No,0,0.0,1.0,0,Highly Urban/ Urban
10292,0,50.0,0,7.0,43445.0,No,149248.0,Yes,F,Bachelors,Home Maker,36,Private,22550.0,6,Minivan,no,0.0,0,No,0,0.0,11.0,0,Highly Urban/ Urban
10293,0,52.0,0,11.0,53235.0,No,197017.0,Yes,F,High School,Clerical,64,Private,19400.0,6,Minivan,no,0.0,0,No,0,0.0,9.0,0,Highly Rural/ Rural

## 📈 Exploratory Data Visualization

In [29]:
# Target Variable Distribution
fig = px.histogram(
    df,
    x='claim_flag',
    color='claim_flag',
    text_auto=True,
    title='Target Variable Distribution'
)
fig.show()

In [30]:
# Claim Rate Overview
claim_rate = (
    df['claim_flag']
    .value_counts()
    .reset_index()
)

claim_rate.columns = ['claim_flag', 'count']

fig = px.pie(
    claim_rate,
    names='claim_flag',
    values='count',
    hole=0.4,
    title='Claim Rate Distribution'
)

fig.show()

In [31]:
# Claim Distribution by Gender
fig = px.histogram(
    df,
    x='gender',
    color='claim_flag',
    barmode='group',
    text_auto=True,
    title='Gender vs Claim'
)

fig.show()

In [32]:
# Claim Distribution by Vehicle Type
fig = px.histogram(
    df,
    x='car_type',
    color='claim_flag',
    barmode='group',
    text_auto=True,
    title='Car Type vs Claim'
)

fig.update_xaxes(categoryorder='total descending')

fig.show()

In [33]:
# Age Distribution by Claim Status
fig = px.box(
    df,
    x='claim_flag',
    y='age',
    color='claim_flag',
    title='Age vs Claim'
)

fig.show()

In [34]:
#  Feature Correlation Matrix
corr_df = df.corr(numeric_only=True).round(2)
px.imshow( corr_df,text_auto=True,color_continuous_scale='RdBu',width=00,height=700).show()

## ⚙️ Data Preprocessing

In [35]:
# Separate numerical and categorical features.
x = df.drop('claim_flag', axis= 1)
y = df['claim_flag']

## Data Leakage

The feature **CLM_AMT** represents the actual claim amount.

Since this information is only available after a claim occurs, using it would leak future information into the model.

Therefore, it was removed before training.

In [36]:
x.drop(['clm_amt'], axis= 1, inplace= True)

- Apply different preprocessing strategies for each feature type.

In [37]:
# RobustScaler was selected because several numerical features contain significant outliers.
# Unlike StandardScaler, it relies on the median and interquartile range, making it more robust.
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.impute import SimpleImputer
numerical_cols = ['yoj', 'car_age']
numerical_pipeline = Pipeline([('Imputer',SimpleImputer(strategy= 'median')),('scaler', RobustScaler()) ])
numerical_pipeline

Pipeline(steps=[('Imputer', SimpleImputer(strategy='median')),
                ('scaler', RobustScaler())])

In [38]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.impute import KNNImputer
numerical_cols_knn = ['kidsdriv', 'age', 'homekids', 'income', 'home_val', 'travtime','bluebook', 'tif', 'mvr_pts' ]
numerical_pipeline_knn = Pipeline([('KNN_Imputer',KNNImputer(n_neighbors=5)),('scaler', RobustScaler()) ])
numerical_pipeline_knn

Pipeline(steps=[('KNN_Imputer', KNNImputer()), ('scaler', RobustScaler())])

In [39]:
# One-Hot Encoding
# Used for low-cardinality categorical features.
from sklearn.preprocessing import OneHotEncoder
onehot_cols = x.select_dtypes(include='object').columns.drop(['education','occupation'])
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore',drop='first')
onehot_pipeline = Pipeline([('Imputer',SimpleImputer(strategy= 'constant', fill_value= 'Other')),('onehot', ohe) ])
onehot_pipeline

Pipeline(steps=[('Imputer',
                 SimpleImputer(fill_value='Other', strategy='constant')),
                ('onehot',
                 OneHotEncoder(drop='first', handle_unknown='ignore',
                               sparse_output=False))])

In [40]:
# Ordinal Encoding
# Used for education because it has a natural order.
from sklearn.preprocessing import OrdinalEncoder
ord_cols =['education']
ord_pipeline = Pipeline([('ordinal_encoder',  OrdinalEncoder(categories= [ ['<High School', 'High School', 'Bachelors', 'Masters', 'PhD'] ])) ])
ord_pipeline

Pipeline(steps=[('ordinal_encoder',
                 OrdinalEncoder(categories=[['<High School', 'High School',
                                             'Bachelors', 'Masters',
                                             'PhD']]))])

In [41]:
# Binary Encoding
# Used for occupation because it contains many unique categories.
from category_encoders import BinaryEncoder
be_cols =['occupation']
be_pipeline = Pipeline([('ordinal_encoder',  BinaryEncoder()) ])
be_pipeline

Pipeline(steps=[('ordinal_encoder', BinaryEncoder())])

In [42]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_pipeline, numerical_cols),
    ('num_knn',numerical_pipeline_knn,numerical_cols_knn),
    ('cat', onehot_pipeline, onehot_cols),
    ('ord',ord_pipeline,ord_cols),
    ('be',be_pipeline,be_cols)], remainder='passthrough', force_int_remainder_cols=False)
preprocessor

ColumnTransformer(force_int_remainder_cols=False, remainder='passthrough',
                  transformers=[('num',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', RobustScaler())]),
                                 ['yoj', 'car_age']),
                                ('num_knn',
                                 Pipeline(steps=[('KNN_Imputer', KNNImputer()),
                                                 ('scaler', RobustScaler())]),
                                 ['kidsdriv', 'age', 'homekids', 'income',
                                  'home_val', 'travtime', 'blu...
                                                                sparse_output=False))]),
                                 Index(['parent1', 'mstatus', 'gender', 'car_use', 'car_type', 'red_car',
       'revoked', 'urbanicity'],
      dtype='object')),
                                ('ord',
                                 Pipeline(steps=[('ordinal_encoder',
                                                  OrdinalEncoder(categories=[['<High '
                                                                              'School',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelors',
                                                                              'Masters',
                                                                              'PhD']]))]),
                                 ['education']),
                                ('be',
                                 Pipeline(steps=[('ordinal_encoder',
                                                  BinaryEncoder())]),
                                 ['occupation'])])

In [43]:
import warnings

warnings.simplefilter("ignore", UserWarning)

In [44]:
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline

# Create Stratified CV
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

models = [
    ('Logistic Regression', LogisticRegression(random_state=42 ,class_weight='balanced')),
    ('Decision Tree', DecisionTreeClassifier(random_state=42 ,class_weight='balanced')),
    ('Random Forest', RandomForestClassifier(random_state=42 ,class_weight='balanced')),
    ('CatBoost', CatBoostClassifier(random_state=42, verbose=0)),
    ('LightGBM', LGBMClassifier(random_state=42 ,class_weight='balanced',verbosity=-1))
]

for model in models:
    
    model_pipeline = Pipeline([
        ('Preprocessing', preprocessor),
        ('Model', model[1])
    ])

    result = cross_validate(
        model_pipeline,
        x,
        y,
        cv=cv,  
        scoring='balanced_accuracy',
        return_train_score=True
    )

    print(model[0])
    print(
        f"Train Balanced Accuracy: {result['train_score'].mean()*100:.2f}%"
    )
    print(
        f"Test Balanced Accuracy: "
        f"{result['test_score'].mean()*100:.2f}% "
        f"(± {result['test_score'].std()*100:.2f})"
    )
    print('-' * 50)

Logistic Regression
Train Balanced Accuracy: 71.97%
Test Balanced Accuracy: 71.86% (± 0.54)
--------------------------------------------------
Decision Tree
Train Balanced Accuracy: 100.00%
Test Balanced Accuracy: 61.62% (± 0.41)
--------------------------------------------------
Random Forest
Train Balanced Accuracy: 100.00%
Test Balanced Accuracy: 63.13% (± 0.71)
--------------------------------------------------
CatBoost
Train Balanced Accuracy: 83.02%
Test Balanced Accuracy: 68.59% (± 0.58)
--------------------------------------------------
LightGBM
Train Balanced Accuracy: 88.09%
Test Balanced Accuracy: 73.77% (± 1.00)
--------------------------------------------------

## 🔍 Hyperparameter Optimization

In [45]:
# LGBMClassifier hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

para_grid = {
    'Model__n_estimators': randint(100, 1000),
    'Model__learning_rate': uniform(0.01, 0.29),   # 0.01 → 0.30
    'Model__max_depth': randint(3, 50),
    'Model__num_leaves': randint(20, 150)
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
model_pipline = Pipeline(steps=[('Preprocessing',preprocessor),('Model',LGBMClassifier(random_state=42,verbosity=-1,class_weight='balanced'))])
random_search = RandomizedSearchCV(estimator=model_pipline, param_distributions=para_grid, n_iter=10, cv=cv, scoring='balanced_accuracy', n_jobs=1, random_state=42)


random_search.fit(x, y)

print("Best Score:", random_search.best_score_)
print("Best Params:", random_search.best_params_)

Best Score: 0.7410339652589412
Best Params: {'Model__learning_rate': np.float64(0.010225842093894155), 'Model__max_depth': 23, 'Model__n_estimators': 260, 'Model__num_leaves': 77}

## 🚀 Train Final Model

In [46]:
final_pipeline = Pipeline(steps=[('Preprocessing',preprocessor),('Model',LGBMClassifier(n_estimators=152,num_leaves=87,max_depth=8,learning_rate=0.079472948293422))])
final_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('Imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['yoj', 'car_age']),
                                                 ('num_knn',
                                                  Pipeline(steps=[('KNN_Imputer',
                                                                   KNNImputer()),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['kidsdriv', 'age',
                                                   'homekids', 'i...
       'revoked', 'urbanicity'],
      dtype='object')),
                                                 ('ord',
                                                  Pipeline(steps=[('ordinal_encoder',
                                                                   OrdinalEncoder(categories=[['<High '
                                                                                               'School',
                                                                                               'High '
                                                                                               'School',
                                                                                               'Bachelors',
                                                                                               'Masters',
                                                                                               'PhD']]))]),
                                                  ['education']),
                                                 ('be',
                                                  Pipeline(steps=[('ordinal_encoder',
                                                                   BinaryEncoder())]),
                                                  ['occupation'])])),
                ('Model',
                 LGBMClassifier(learning_rate=0.079472948293422, max_depth=8,
                                n_estimators=152, num_leaves=87))])

In [47]:
# The following plot illustrates the twenty most influential features used by the LightGBM model.
feature_names = final_pipeline.named_steps[
    'Preprocessing'
].get_feature_names_out()

importance = final_pipeline.named_steps[
    'Model'
].feature_importances_

importance_df = (
    pd.DataFrame({
        'Feature': feature_names,
        'Importance': importance
    })
    .sort_values('Importance', ascending=False)
    .head(20)
)

fig = px.bar(
    importance_df,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Top 20 Important Features'
)

fig.update_layout(yaxis={'categoryorder': 'total ascending'})

fig.show()

# 🎯 Final Conclusion

This notebook demonstrated a complete machine learning workflow for predicting car insurance claims.

Key findings:

- Cleaned and standardized the raw dataset.
- Applied different preprocessing techniques depending on feature type.
- Compared five machine learning algorithms.
- LightGBM achieved the best balanced accuracy.
- Hyperparameter tuning further improved the model.
- Previous claims, driving history, and vehicle-related features were among the most important predictors.

Future work may include:

- Advanced feature engineering.
- Stacking models.
- Optuna hyperparameter optimization.
- Probability calibration.